local animID = {}
    animID[0] = { name="STOP", id=0 };
    animID[1] = { name="COMBINE", id=1 };
    animID[2] = { name="PICKUP_LOWER", id=2 };
    animID[3] = { name="PICKUP_MIDDLE", id=3 };
    animID[4] = { name="PICKUP_UPPER", id=4 };
    animID[5] = { name="HANDSHEAD_KNEEL", id=5 };
    animID[6] =	{ name="HANDSHEAD_STAND", id=6 };
    animID[7] =	{ name="HANDSUP_KNEEL", id=7 };
    animID[8] =	{ name="HANDSUP_STAND", id=8 };
    animID[9] =	{ name="ENTERCODE", id=9 };
    animID[10] = { name="VOMIT", id=10 };
    animID[11] = { name="CROSSARMS", id=11 };
    animID[12] = { name="DABSAREGAY", id=12 };
    animID[13] = { name="DONTKNOW", id=13 };
    animID[14] = { name="DUSTOFF", id=14 };
    animID[15] = { name="FACEPALM", id=15 };
    animID[16] = { name="IDONTLISTEN", id=16 };
    animID[17] = { name="FLEXX", id=17 };
    animID[18] = { name="HALTSTOP", id=18 };
    animID[19] = { name="INEAR_COMM", id=19 };
    animID[20] = { name="ITSJUSTRIGHT", id=20 };
    animID[21] = { name="FALLONKNEES", id=21 };
    animID[22] = { name="KUNGFU", id=22 };
    animID[23] = { name="CALLME", id=23 };
    --[[animID[0] = 	{ name="SALUTE", id=24 };
    animID[0] = 	{ name="SHOOSH", id=25 };
    animID[0] = 	{ name="SLAPOWNASS", id=26 };
    animID[0] = 	{ name="SLAPOWNASS2", id=27 };
    animID[0] =   { name="THROATSLIT", id=28 };
    animID[0] = 	{ name="THUMBSUP", id=29 };
    animID[0] = 	{ name="WAVE3", id=30 };
    animID[0] = 	{ name="WIPEOFFSWEAT", id=31 };
    animID[0] = 	{ name="KICKDOOR", id=32 },
    animID[0] = 	{ name="LOCKDOOR", id=33 },
    animID[0] = 	{ name="CRAZYMAN", id=34 },
    animID[0] = 	{ name="DARKSOULS", id=35 },
    animID[0] =   { name="SMOKING", id=36 },
    animID[0] =    { name="CLAP", id=37 },
    animID[0] = 	{ name="SIT01", id=38 },
    animID[0] = 	{ name="SIT02", id=39 },
    animID[0] = 	{ name="SIT03", id=40 },
    animID[0] = 	{ name="SIT04", id=41 },
    animID[0] = 	{ name="SIT05", id=42 },
    animID[0] = 	{ name="SIT06", id=43 },
    animID[0] = 	{ name="SIT07", id=44 },
    animID[0] = 	{ name="LAY01", id=45 },
    animID[0] =   { name="LAY02", id=46 },
    animID[0] = 	{ name="LAY03", id=47 },
    animID[0] = 	{ name="LAY04", id=48 },
    animID[0] = 	{ name="LAY05", id=49 },
    animID[0] = 	{ name="LAY06", id=50 },
    animID[0] = 	{ name="LAY07", id=51},
    animID[0] = 	{ name="LAY08", id=52 },
    animID[0] = 	{ name="LAY09", id=53 },
    animID[0] = 	{ name="LAY010", id=54 },
    animID[0] = 	{ name="LAY011", id=55 },
    animID[0] = 	{ name="LAY012", id=56 },
    animID[0] = 	{ name="LAY013", id=57 },
    animID[0] = 	{ name="LAY014", id=58 },
	animID[0] = { name="LAY015", id=59 },
    animID[0] = 	{ name="LAY016", id=60 },
    animID[0] = 	{ name="LAY017", id=61 },
    animID[0] = 	{ name="LAY018", id=62 },
    animID[0] =    { name="WAVE", id=63 },
    animID[0] = 	{ name="WAVE2", id=64 },
    animID[0] = 	{ name="STRETCH", id=65 },
    animID[0] = 	{ name="BOW", id=66 },
    animID[0] = 	{ name="CALL_GUARDS", id=67 },
    animID[0] = 	{ name="CALL_SOMEONE", id=68 },
    animID[69] = 	{ name="CALL_SOMEONE2", id=69 },
    animID[70] = 	{ name="CHECK_EQUIPMENT", id=70 },]]
    animID[71] =    { name="CHECK_EQUIPMENT2", id=71 };
